services:
  esp-mqtt-telegram:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esp-mqtt-telegram-app
    restart: unless-stopped
    environment:
      - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CONFIG_FILE=${CONFIG_FILE:-esp_config.json}
      - APP_RELOAD=false
    volumes:
      - ./logs:/app/logs
      - ./esp_config.json:/app/esp_config.json
    networks:
      - esp-network


networks:
  esp-network:
    external: true